source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JKLGenericBuilder-ObjC_Example', :exclusive => true do
  pod 'JKLGenericBuilder-ObjC', :path => '../'
end

target 'JKLGenericBuilder-ObjC_Tests', :exclusive => true do
  pod 'JKLGenericBuilder-ObjC', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
